apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: spring-apiserver
  labels:
    app: keycloak
spec:
  realmSelector:
    matchLabels:
      app: keycloak
  client:
    clientAuthenticatorType: client-secret
    enabled: true
    name: spring-apiserver
    clientId: spring-apiserver
    redirectUris:
      - 'https://apiserver-app.apps.aws-ipi.sandbox1044.opentlc.com/*'
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: true
    protocol: openid-connect
    protocolMappers:
      - name: username
        protocol: openid-connect
        protocolMapper: oidc-usermodel-property-mapper
        config:
          "userinfo.token.claim": "true"
          "user.attribute": "username"
          "id.token.claim": "true"
          "access.token.claim": "true"
          "claim.name": "preferred_username"
          "jsonType.label": "String"
          