apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
    name: default
    namespace: knative-eventing
spec:
    defaultBrokerClass: Kafka
    config:
        config-br-defaults:
            default-br-config: |
                clusterDefault:
                    apiVersion: v1
                    brokerClass: Kafka
                    kind: ConfigMap
                    name: kafka-broker-config
                    namespace: knative-eventing