---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
  namespace: cert-manager
spec:
  secretName: ca-root-keypair
  commonName: ca-root
  isCA: true
  dnsNames:
  - ca-root
  subject:
    organizationalUnits:
    - kubernetes
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io