kind: CheCluster
apiVersion: org.eclipse.che/v1
metadata:
  name: crw
  namespace: crw
spec:
  server:
    workspaceNamespaceDefault: crw-<username>
    # workspacesDefaultPlugins:
    #   - editor: ''
    #     plugins:
    #       - ''
  database:
    externalDb: false
  auth:
    externalIdentityProvider: false
    # openShiftoAuth: true
    # initialOpenShiftOAuthUser: true
  storage:
    pvcStrategy: common
    pvcClaimSize: 10Gi
    preCreateSubPaths: false
  devWorkspace:
    enable: true
  metrics:
    enable: true
  imagePuller:
    enable: false