apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: keycloak
spec:
  hostname: keycloak.cluster1.joshgav.com
  tlsSecret:
    name: keycloak-tls-keypair
  requestPolicy:
    insecure:
      action: Redirect