apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- patches/argocd-tls-keypair_host_patch.yaml
- patches/argocd-tls-keypair_ingress_patch.yaml