kind: ArgoCD
apiVersion: argoproj.io/v1alpha1
metadata:
  name: gitops-operator
spec:
  controller: {}
  dex:
    openShiftOAuth: true
  ha:
    enabled: false
  rbac: {}
  redis: {}
  repo: {}
  server:
    route:
      enabled: true
