apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: argocd
spec:
  hostname: argocd.cluster1.joshgav.com
  tlsSecret:
    name: argocd-secret
  requestPolicy:
    insecure:
      action: Redirect