apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.4.0
- host.yaml
- ingress.yaml
patchesStrategicMerge:
- patches/argocd-application-controller_patch.yaml
- patches/argocd-server_patch.yaml