apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: apiserver
spec:
  hostname: apiserver.cluster1.joshgav.com
  tlsSecret:
    name: apiserver-tls-keypair
  requestPolicy:
    insecure:
      action: Redirect