apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
- ./base

# configMapGenerator:
# - name: db-init-sql
#   behavior: create
#   files:
#   - ./base/init.sql
#   options:
#     disableNameSuffixHash: true
