apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: dbinstance1
spec:
  forProvider:
    region: us-east-2
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    autogeneratePassword: true
    backupRetentionPeriod: 1
    dbInstanceClass: db.t3.micro
    dbName: exampledb
    engine: postgres
    engineVersion: "14.2"
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      key: password
      name: dbinstance1-password
      namespace: crossplane-system
    preferredBackupWindow: "7:00-8:00"
    preferredMaintenanceWindow: "Sat:8:00-Sat:11:00"
    publiclyAccessible: false
    skipFinalSnapshot: true
    storageEncrypted: false
    storageType: gp2
    applyImmediately: true
  writeConnectionSecretToRef:
    name: instance1-binding
    namespace: default
  providerConfigRef:
    name: providerconfig-aws