apiVersion: v1
kind: Service
metadata:
  name: idm-ldap
spec:
  type: ClusterIP
  selector:
    app: idm
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: 636
